apiVersion: 1
datasources:
  - name: ClickHouse
    type: alextrv/clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    username: ${CLICKHOUSE_USERNAME:-default}
    password: ${CLICKHOUSE_PASSWORD:-}
